### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by exaline-ru** [SynderDEV/october-blogcustoms-plugin#1]
Error during installation:

`php artisan plugin:install synder.blogcustoms
Installing Plugin: synder.blogcustoms
Executing: composer require synder/blogcustoms-plugin

Using version ^1.0 for synder/blogcustoms-plugin
./composer.json has been updated
Running composer update synder/blogcustoms-plugin
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - synder/blogcustoms-plugin[1.0.0, ..., 1.0.2] require rainlab/blog-plugin ~1.2.0 -> found rainlab/blog-plugin[dev-master, dev-backend-ui-style, dev-build419, v1.3.1, ..., v1.5.1] but it does not match the constraint.
    - Root composer.json requires synder/blogcustoms-plugin ^1.0 -> satisfiable by synder/blogcustoms-plugin[1.0.0, 1.0.1, 1.0.2].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
`

**Comment by Smirnoy** [comment]
Hello,

thanks for your report. The problem has been solved in version 1.0.3, please give it another try, it should now work seamless.

Sincerely,
~ Sam.

**Comment by exaline-ru** [comment]
Thank you for your promptness! It's working now.
